### ISSUE TITLE
HAADJ does not seem to be possible with Cloud Sync

### ISSUE THREAD

**Issue by hennibadger16** [shehanperera85/IntuneMaps#3]
Hi, 

great work. Just one thing that seems off to me:

Under device join -> HAADJ there is "Azure AD cloud sync" listed. That seems to be wrong to me as the cloud sync agent explicitly does not support device objects.

I'm desperately searching for a way to get users in a disconnected trustless (M&A) forest setup to sync to common tenant but will also need all devices hybrid joined. 

That does not seem to be possible without going for a trust and connect sync.

If it is, I'm gladly wrong here if you can tell me how to get there :-D

Thanks again for the great work!

**Comment by shehanperera85** [comment]
Hello,

Thanks you and I think you are right. Thanks for pointing that out. Will do the change so it will not be under HAADJ.
And true, its wonderful if MSFT introduce the feature in Cloud Sync as most of the organizations still in that Hybrid era before they want to fully move in to the AAD Joined.

Cheers!
Shehan.
